### ISSUE TITLE
Netatmo extra2

### ISSUE THREAD

**Issue by gsainton** [matthewwall/weewx-netatmo#14]
Hi,
I'm using Weewx an Netatmo weather station. All works fine. But I have a second extramodule, but how my I have this extramodule data in Weewx ?

My I need to modify netatmo.py and add more field data ? 
        'extraTemp2':           '*.NAModule5.Temperature',
        'extraHumid2':          '*.NAModule5.Humidity',
        'extra_rf_status_2':    '*.NAModule5.rf_status',
        'extra_battery_vp_2':   '*.NAModule5.battery_vp',
        'extra2BatteryStatus':  '*.NAModule5.battery_percent',

My I rebuild my SQL database ?

Thank's for your help.

Gilles.

**Comment by matthewwall** [comment]
this is for bug reports.  for support, please post to weewx-user

do not modify netatmo.py.  modify the [Netatmo] section of your weewx configuration file like this:

```
[Netatmo]
    ...
    [[sensor_map]]
        extraTemp2 = *.NAModule5.Temperature
        extraHumid2 = *.NAModule5.Humidity
        extra_rf_status_2 = *.NAModule5.rf_status
        extra_battery_vp_2 = *.NAModule5.battery_vp
        extra2BatteryStatus = *.NAModule5.battery_percent
```
