### ISSUE TITLE
Netatmo API Security Update - Aug 4 2022

### ISSUE THREAD

**Issue by WiggyToo** [matthewwall/weewx-netatmo#19]
Hi - not sure this is an issue, or just a case of using new credentials, but Netatmo sent this email below recently.

Does this affect weewx-netatmo?

Thanks

Dear Netatmo developer,
--
To improve the security of our products, we inform you that the Client Credentials grant type method will be completely removed. It will no longer be possible to authenticate with the username and password of the user. The effective date of this update is October 2022.

https://dev.netatmo.com/apidocumentation/oauth#authorization-code

**Comment by bricebou** [comment]
@matthewwall will there be any update of this Netatmo plugin for WeeWX ? Thanks a lot :)

**Comment by WiggyToo** [comment]
Fix is here 

https://github.com/matthewwall/weewx-netatmo/issues/21

Gav
