### ISSUE TITLE
Mixed up data if more than one NETATMO Station found

### ISSUE THREAD

**Issue by jkrasinger** [matthewwall/weewx-netatmo#7]
I'm using two NETATMO Stations, one with indoor+outdoor module, the second with indoor+outdoor+rain module.
I installed weewx + weewx-netatmo modules and configured the NETATMO part, no other configurations were done by me.
After starting weewx service i got the first generated reports after about 5 mins with data.
After checking the Data i found interesting mix of output, i.e. Outside temp from Module 1, inside temp from Module 2, and so on.

Is there any problem with the weewx-netatmo module when there is more than one NETATMO station?

Here some log-output from debugging test mode:

Jun 16 17:49:58 xubuntu-zfs wee_netatmo[8599]: netatmo: netatmo-client: url: https://api.netatmo.net/api/getstationsdata data: access_token=546d95881977598d5eb3d860%7C1beba35d4b9632ed7918a36bdeee9383 hdr: {'Content-Type': 'application/x-www-form-urlencoded;charset=utf-8'}
Jun 16 17:49:59 xubuntu-zfs wee_netatmo[8599]: netatmo: netatmo-client: resp_obj: {u'body': {u'user': {u'mail': u'johann@krasinger.com', u'administrative': {u'lang': u'de-DE', u'reg_locale': u'de-AT', u'windunit': 0, u'feel_like_algo': 0, u'pressureunit': 0, u'country': u'AT', u'unit': 0}}, u'devices': [{u'last_setup': 1416468284, u'data_type': [u'Temperature', u'CO2', u'Humidity', u'Noise', u'Pressure'], u'last_upgrade': 1439971552, u'firmware': 132, u'date_setup': 1416468284, u'modules': [{u'last_setup': 1416468242, u'rf_status': 71, u'data_type': [u'Temperature', u'Humidity'], u'last_message': 1529164091, u'firmware': 44, u'dashboard_data': {u'date_min_temp': 1529118734, u'Temperature': 23.4, u'time_utc': 1529164053, u'temp_trend': u'stable', u'Humidity': 50, u'date_max_temp': 1529143189, u'min_temp': 12.5, u'max_temp': 27.4}, u'module_name': u'Au\xdfenmodul', u'battery_vp': 5240, u'_id': u'02:00:00:04:e5:cc', u'type': u'NAModule1', u'battery_percent': 68, u'last_seen': 1529164053}], u'co2_calibrating': False, u'last_status_store': 1529164099, u'wifi_status': 17, u'place': {u'timezone': u'Europe/Vienna', u'city': u'Linz', u'altitude': 261, u'location': [14.3130331, 48.2550091], u'country': u'AT'}, u'dashboard_data': {u'CO2': 2058, u'Temperature': 23, u'time_utc': 1529164059, u'pressure_trend': u'down', u'temp_trend': u'stable', u'Humidity': 66, u'Pressure': 1009.8, u'Noise': 38, u'AbsolutePressure': 979, u'date_max_temp': 1529107528, u'min_temp': 20.1, u'date_min_temp': 1529126331, u'max_temp': 23.1}, u'cipher_id': u'enc:16:CCPhlZ4LjzbYveTobgYmd53oavmNAL3es2AcfP8xH+NVTY2PiyOFzH+/2KmZ5udd', u'module_name': u'Indoor', u'station_name': u'Wetter-LK', u'_id': u'70:ee:50:04:cb:c2', u'type': u'NAMain'}, {u'last_setup': 1524835848, u'data_type': [u'Temperature', u'CO2', u'Humidity', u'Noise', u'Pressure'], u'last_upgrade': 1525498902, u'firmware': 134, u'date_setup': 1524835848, u'modules': [{u'last_setup': 1524835614, u'rf_status': 74, u'data_type': [u'Temperature', u'Humidity'], u'last_message': 1529163885, u'firmware': 46, u'dashboard_data': {u'date_min_temp': 1529113641, u'Temperature': 12.5, u'time_utc': 1529163834, u'temp_trend': u'down', u'Humidity': 84, u'date_max_temp': 1529138763, u'min_temp': 8, u'max_temp': 21.2}, u'module_name': u'Outdoor-Reunion', u'battery_vp': 5954, u'_id': u'02:00:00:2c:e9:56', u'type': u'NAModule1', u'battery_percent': 98, u'last_seen': 1529163885}, {u'last_setup': 1525938257, u'rf_status': 73, u'data_type': [u'Rain'], u'last_message': 1529163885, u'firmware': 8, u'dashboard_data': {u'time_utc': 1529163872, u'sum_rain_24': 0, u'sum_rain_1': 0, u'Rain': 0}, u'module_name': u'LK-Reunion-Rain', u'battery_vp': 6044, u'_id': u'05:00:00:04:64:b0', u'type': u'NAModule3', u'battery_percent': 100, u'last_seen': 1529163885}], u'co2_calibrating': False, u'last_status_store': 1529163891, u'wifi_status': 55, u'place': {u'timezone': u'Indian/Reunion', u'city': u'La Plaine des Cafres', u'altitude': 1323, u'location': [55.5607501, -21.236416], u'country': u'RE'}, u'dashboard_data': {u'CO2': 505, u'Temperature': 20.8, u'time_utc': 1529163880, u'pressure_trend': u'stable', u'temp_trend': u'stable', u'Humidity': 60, u'Pressure': 1033.6, u'Noise': 43, u'AbsolutePressure': 881.4, u'date_max_temp': 1529155413, u'min_temp': 18.4, u'date_min_temp': 1529122153, u'max_temp': 21.8}, u'cipher_id': u'enc:16:58sD8hoDQHY0W158VIn4UafeyoqdH65MiKbOMmIAv7SumpZfDfNHTal/bvkn11Qv', u'module_name': u'Indoor', u'station_name': u'JK-Reunion', u'_id': u'70:ee:50:2c:d3:d6', u'type': u'NAMain'}]}, u'status': u'ok', u'time_exec': 0.12150311470032, u'time_server': 1529164198}
Jun 16 17:49:59 xubuntu-zfs wee_netatmo[8599]: netatmo: netatmo-client: cloud units: {'windunit': 0, 'unit': 0, 'pressureunit': 0}
Jun 16 17:49:59 xubuntu-zfs wee_netatmo[8599]: netatmo: netatmo-client: next update in 300 seconds
Jun 16 17:49:59 xubuntu-zfs wee_netatmo[8599]: netatmo: MainThread: data: {u'70:ee:50:04:cb:c2.NAMain.Noise': 38, u'02:00:00:2c:e9:56.NAModule1.last_seen': 1529163885, u'02:00:00:04:e5:cc.NAModule1._id': u'02:00:00:04:e5:cc', u'02:00:00:04:e5:cc.NAModule1.Humidity': 50, u'70:ee:50:2c:d3:d6.NAMain.date_setup': 1524835848, u'05:00:00:04:64:b0.NAModule3.last_setup': 1525938257, u'70:ee:50:04:cb:c2.NAMain.date_setup': 1416468284, u'02:00:00:2c:e9:56.NAModule1.last_setup': 1524835614, u'02:00:00:2c:e9:56.NAModule1.firmware': 46, u'02:00:00:04:e5:cc.NAModule1.battery_percent': 68, u'70:ee:50:2c:d3:d6.NAMain.firmware': 134, u'05:00:00:04:64:b0.NAModule3.Rain': 0.0, u'02:00:00:2c:e9:56.NAModule1.Temperature': 12.5, u'70:ee:50:2c:d3:d6.NAMain.wifi_status': 55, u'70:ee:50:2c:d3:d6.NAMain.CO2': 505, u'02:00:00:04:e5:cc.NAModule1.module_name': u'Au\xdfenmodul', u'02:00:00:04:e5:cc.NAModule1.battery_vp': 5240, u'70:ee:50:2c:d3:d6.NAMain.co2_calibrating': False, u'70:ee:50:04:cb:c2.NAMain.CO2': 2058, u'05:00:00:04:64:b0.NAModule3.sum_rain_24': 0.0, u'05:00:00:04:64:b0.NAModule3.battery_percent': 100, u'70:ee:50:2c:d3:d6.NAMain.AbsolutePressure': 881.4, u'70:ee:50:2c:d3:d6.NAMain.Noise': 43, u'70:ee:50:2c:d3:d6.NAMain.time_utc': 1529163880, u'70:ee:50:04:cb:c2.NAMain.Humidity': 66, u'05:00:00:04:64:b0.NAModule3.time_utc': 1529163872, u'70:ee:50:2c:d3:d6.NAMain._id': u'70:ee:50:2c:d3:d6', u'02:00:00:2c:e9:56.NAModule1._id': u'02:00:00:2c:e9:56', u'70:ee:50:04:cb:c2.NAMain.AbsolutePressure': 979, u'05:00:00:04:64:b0.NAModule3.battery_vp': 6044, u'70:ee:50:04:cb:c2.NAMain._id': u'70:ee:50:04:cb:c2', u'02:00:00:04:e5:cc.NAModule1.Temperature': 23.4, u'70:ee:50:04:cb:c2.NAMain.last_status_store': 1529164099, u'70:ee:50:04:cb:c2.NAMain.Temperature': 23, u'02:00:00:2c:e9:56.NAModule1.module_name': u'Outdoor-Reunion', u'70:ee:50:04:cb:c2.NAMain.last_setup': 1416468284, u'70:ee:50:04:cb:c2.NAMain.time_utc': 1529164059, u'05:00:00:04:64:b0.NAModule3.rf_status': 73, u'02:00:00:04:e5:cc.NAModule1.rf_status': 71, u'70:ee:50:2c:d3:d6.NAMain.module_name': u'Indoor', u'70:ee:50:2c:d3:d6.NAMain.Temperature': 20.8, u'02:00:00:04:e5:cc.NAModule1.last_seen': 1529164053, u'02:00:00:04:e5:cc.NAModule1.last_setup': 1416468242, u'70:ee:50:04:cb:c2.NAMain.last_upgrade': 1439971552, u'70:ee:50:2c:d3:d6.NAMain.Humidity': 60, u'70:ee:50:04:cb:c2.NAMain.wifi_status': 17, u'05:00:00:04:64:b0.NAModule3._id': u'05:00:00:04:64:b0', u'70:ee:50:04:cb:c2.NAMain.firmware': 132, u'02:00:00:04:e5:cc.NAModule1.firmware': 44, u'02:00:00:2c:e9:56.NAModule1.Humidity': 84, u'70:ee:50:04:cb:c2.NAMain.module_name': u'Indoor', u'05:00:00:04:64:b0.NAModule3.last_seen': 1529163885, u'70:ee:50:04:cb:c2.NAMain.Pressure': 1009.8, u'70:ee:50:2c:d3:d6.NAMain.last_setup': 1524835848, u'02:00:00:2c:e9:56.NAModule1.battery_vp': 5954, u'05:00:00:04:64:b0.NAModule3.module_name': u'LK-Reunion-Rain', u'02:00:00:2c:e9:56.NAModule1.time_utc': 1529163834, u'70:ee:50:04:cb:c2.NAMain.co2_calibrating': False, u'02:00:00:2c:e9:56.NAModule1.battery_percent': 98, u'70:ee:50:2c:d3:d6.NAMain.Pressure': 1033.6, u'70:ee:50:2c:d3:d6.NAMain.last_status_store': 1529163891, u'05:00:00:04:64:b0.NAModule3.firmware': 8, u'05:00:00:04:64:b0.NAModule3.sum_rain_1': 0.0, u'02:00:00:04:e5:cc.NAModule1.time_utc': 1529164053, u'02:00:00:2c:e9:56.NAModule1.rf_status': 74, u'70:ee:50:2c:d3:d6.NAMain.last_upgrade': 1525498902}
Jun 16 17:49:59 xubuntu-zfs wee_netatmo[8599]: netatmo: MainThread: packet: {'inTemp': 23, 'noise': 38, 'co2': 505, 'outTemp': 12.5, 'outHumidity': 50, 'outTempBatteryStatus': 68, 'rain': 0.0, 'dateTime': 1529164199, 'pressure': 881.4, 'wifi_status': 55, 'rain_rf_status': 73, 'out_battery_vp': 5240, 'rain_battery_vp': 6044, 'inHumidity': 66, 'rainBatteryStatus': 100, 'rain_total': 0.0, 'usUnits': 16, 'out_rf_status': 71}
Jun 16 17:50:50 xubuntu-zfs weewx[25402]: manager: Added record 2018-06-16 17:50:00 CEST (1529164200) to database 'weewx.sdb'
Jun 16 17:50:50 xubuntu-zfs weewx[25402]: manager: Added record 2018-06-16 17:50:00 CEST (1529164200) to daily summary in 'weewx.sdb'

**Comment by matthewwall** [comment]
in the default configuration, the weewx-netatmo driver will accept all data from every netatmo station, and it will not distinguish between them.

the sensors are distinguished by their MAC addresses.  it looks like you have these MAC addresses:
```
05:00:00:04:64:b0 NAModule3
02:00:00:04:e5:cc NAModule1
02:00:00:2c:e9:56 NAModule1
70:ee:50:2c:d3:d6 NAMain
70:ee:50:04:cb:c2 NAMain
```
so the confusion arises because data from the two NAMain and the two NAModule1 are being combined.

you should either (1) map the data from each station into separate fields of the database, or (2) run a separate weewx instance for each netatmo station, each with station-specific identifiers.

for example, to do option (2), one configuration file would something like contain this:
```
[Netatmo]
    ...
    [[sensor_map]]
        pressure=70:ee:50:04:cb:c2.NAMain.AbsolutePressure
        inTemp=70:ee:50:04:cb:c2.NAMain.Temperature
        inHumidity=70:ee:50:04:cb:c2.NAMain.Humidity
        ...
        outTemp=02:00:00:04:e5:cc.NAModule1.Temperature
        outHumidity=02:00:00:04:e5:cc.NAModule1.Humidity
        ...
```
and the other would contain something like this:
```
[Netatmo]
    ...
    [[sensor_map]]
        pressure=70:ee:50:2c:d3:d6.NAMain.AbsolutePressure
        inTemp=70:ee:50:2c:d3:d6.NAMain.Temperature
        inHumidity=70:ee:50:2c:d3:d6.NAMain.Humidity
        ...
        outTemp=02:00:00:2c:e9:56.NAModule1.Temperature
        outHumidity=02:00:00:2c:e9:56.NAModule1.Humidity
        ...
```
does that help?

m

**Comment by jkrasinger** [comment]
Thank you for looking into this issue. Your answer give me some ideas for the reason of my problem and how to solve it.
I was trying weewx and your plugin more or less unconfigured. So i think i must do some more readings regarding configuration of weewx and this plugin.

Hopefully i will find the informations how to map the data to different fields, otherwise i'll try to run multiple instances.

Thanks, Jonny

**Comment by jkrasinger** [comment]
Reconfigured weewx as outlined by you ... now all is working.

Thank you for the help

Jonny
