### ISSUE TITLE
No Update on DB

### ISSUE THREAD

**Issue by bawe** [matthewwall/weewx-netatmo#8]
No Update on DB since Today 15:42.

Log;
Nov 20 16:28:45 weewx2 weewx[1198]: netatmo: netatmo-client: cloud units: {'windunit': 0, 'unit': 0, 'pressureunit': 0}
Nov 20 16:28:45 weewx2 weewx[1198]: netatmo: netatmo-client: exception in netatmo-client: 'dashboard_data'
Nov 20 16:28:45 weewx2 weewx[1198]: *** Traceback (most recent call last):
Nov 20 16:28:45 weewx2 weewx[1198]: ***   File "/usr/share/weewx/user/netatmo.py", line 319, in collect_data
Nov 20 16:28:45 weewx2 weewx[1198]: ***     CloudClient.get_data(self._sd, self._device_id)
Nov 20 16:28:45 weewx2 weewx[1198]: ***   File "/usr/share/weewx/user/netatmo.py", line 349, in get_data
Nov 20 16:28:45 weewx2 weewx[1198]: ***     data = CloudClient.extract_data(d, units_dict)
Nov 20 16:28:45 weewx2 weewx[1198]: ***   File "/usr/share/weewx/user/netatmo.py", line 364, in extract_data
Nov 20 16:28:45 weewx2 weewx[1198]: ***     if 'time_utc' in x['dashboard_data']:
Nov 20 16:28:45 weewx2 weewx[1198]: *** KeyError: 'dashboard_data'
Nov 20 16:28:45 weewx2 weewx[1198]: netatmo: netatmo-client: failed to get data after 5 attempts
Nov 20 16:28:45 weewx2 weewx[1198]: netatmo: netatmo-client: next update in 300 seconds

root@weewx2 ~ # wee_extension --list
Extension Name    Version   Description
netatmo           0.12      Driver for netatmo weather stations.

**Comment by bawe** [comment]
works again without any actions - stange..

**Comment by bawe** [comment]
issue is back

**Comment by jkrasinger** [comment]
Have same problem starting on Nov 20th at about 15:30 CET. Since this time nothing is logged to DB becauseof this error.
Has anything changed on Netatmo side?

**Comment by jkrasinger** [comment]
Used by mistake Driver Version 0.11 instead of 0.12. After recreating my docker container with new Version now the error changed to:

weewx[13]: engine: Starting main packet loop.
weewx[13]: netatmo: netatmo-client: exception in netatmo-client: 'dashboard_data'
weewx[13]: netatmo: netatmo-client: exception in netatmo-client: 'dashboard_data'
weewx[13]: netatmo: netatmo-client: exception in netatmo-client: 'dashboard_data'
weewx[13]: netatmo: netatmo-client: exception in netatmo-client: 'dashboard_data'
weewx[13]: netatmo: netatmo-client: exception in netatmo-client: 'dashboard_data'
weewx[13]: netatmo: netatmo-client: failed to get data after 5 attempts

**Comment by bawe** [comment]
Can anyone help? What informations are necessary?

**Comment by bawe** [comment]
I think I found the issue:

Wind -> reachable:True
{  
                  u'last_setup':1542307841,
                  u'rf_status':86,
                  u'data_type':[  
                     u'Wind'
                  ],
                  u'last_message':1544455525,
                  u'firmware':19,
                  u'reachable':True,
                  u'dashboard_data':{  
                     u'max_wind_angle':214,
                     u'date_max_wind_str':1544406953,
                     u'max_wind_str':28
                  },
                  u'module_name':u'Wind',
                  u'battery_vp':5927,
                  u'_id':                  u'06:00:00:02:                  da:18                  ', u'                  type':u'NAModule2',
                  u'battery_percent':96,
                  u'last_seen':1544455525
               }

Wind -> reachable:False
{  
                  u'last_setup':1542307841,
                  u'rf_status':86,
                  u'data_type':[  
                     u'Wind'
                  ],
                  u'last_message':1544455525,
                  u'firmware':19,
                  u'reachable':False,
                  u'module_name':u'Wind',
                  u'battery_vp':5927,
                  u'_id':                  u'06:00:00:02:                  da:18                  ', u'                  type':u'NAModule2',
                  u'battery_percent':96,
                  u'last_seen':1544455525
               },

So if an modul is not reachable the "dashboard_data" are not found.

my fix: in /usr/share/weewx/user/netatmo.py
    def extract_data(x, units_dict):
        """Extract data we care about from a device or module"""
        data = dict()
->        if 'dashboard_data' not in x:
->           return data
        if 'time_utc' in x['dashboard_data']:

**Comment by jkrasinger** [comment]
Perfect @bawe , tested your change in my containers and it's working again.
Would be fine to make this change permanent in repo.

**Comment by matthewwall** [comment]
fixed in the repo at commit ed38612

thank you both for tracking this down!

**Comment by jkrasinger** [comment]
Thank you @matthewwall for implementing fix permanently to the code.
